# Generated by Django 3.2.12 on 2022-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbEquipment',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('equip_number', models.CharField(db_column='EQUIP_NUMBER', max_length=15)),
                ('equip_type_number', models.CharField(db_column='EQUIP_TYPE_NUMBER', max_length=3)),
                ('creater_name', models.CharField(blank=True, db_column='CREATER_NAME', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TbInformation',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('equip_type_number', models.CharField(db_column='EQUIP_TYPE_NUMBER', max_length=3)),
                ('equip_name', models.CharField(db_column='EQUIP_NAME', max_length=30)),
                ('equip_manual', models.CharField(db_column='EQUIP_MANUAL', max_length=200)),
                ('equip_notion', models.CharField(db_column='EQUIP_NOTION', max_length=100)),
            ],
        ),
    ]
